name: agrodata_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependencias existentes
  image_picker: ^1.0.4
  http: ^0.13.6
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  video_player: ^2.7.0
  url_launcher: ^6.2.5
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.8

  # Nuevas dependencias para funcionalidad de cultivos
  speech_to_text: ^7.0.0
  permission_handler: ^11.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/